"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { dashboardAPI } from "@/lib/api";
import { LedgerHeader } from "@/components/ledger/LedgerHeader";
import { LedgerStats } from "@/components/ledger/LedgerStats";
import { LedgerFilters } from "@/components/ledger/LedgerFilters";
import { LedgerTable } from "@/components/ledger/LedgerTable";
import { LedgerDrawer } from "@/components/ledger/LedgerDrawer";
import { LedgerPagination } from "@/components/ledger/LedgerPagination";
import { LedgerEmptyState } from "@/components/ledger/LedgerEmptyState";
import { LedgerLoadingState } from "@/components/ledger/LedgerLoadingState";

export default function StudentMealLedgerPage() {
  const router = useRouter();
  const [organization, setOrganization] = useState(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  // Backend response states
  const [ledgerData, setLedgerData] = useState({
    kpi: {
      activeStudents: 0,
      totalMealsServed: 0,
      monthlyRevenue: 0,
      avgStudentBill: 0,
      todayRevenue: 0,
    },
    sections: ["Breakfast", "Lunch", "Snacks", "Dinner"],
    students: [],
    pagination: {
      currentPage: 1,
      pageSize: 10,
      totalStudents: 0,
      totalPages: 1,
    },
  });

  const [selectedStudent, setSelectedStudent] = useState(null);

  // Filters state
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedMonth, setSelectedMonth] = useState("July");
  const [selectedYear, setSelectedYear] = useState("2026");
  const [currentPage, setCurrentPage] = useState(1);

  /* ================= LOAD ORGANIZATION ================= */
  useEffect(() => {
    const stored = localStorage.getItem("organization");
    if (!stored) {
      router.push("/Signup/org");
      return;
    }

    const org = JSON.parse(stored);
    if (org.type !== "organization") {
      alert("Invalid organization session");
      router.push("/Signup/org");
      return;
    }

    setOrganization(org);
  }, [router]);

  /* ================= FETCH BACKEND MONTHLY LEDGER ================= */
  const fetchMonthlyLedger = useCallback(async () => {
    if (!organization) return;

    setLoading(true);
    try {
      const res = await dashboardAPI.monthlyLedger(organization.organizationId, {
        month: selectedMonth,
        year: selectedYear,
        search: searchTerm,
        page: currentPage,
        limit: 10,
      });

      if (res.data) {
        setLedgerData(res.data);
      }
    } catch (err) {
      console.error("Backend Ledger API Error:", err);
      // Fallback empty structure
      setLedgerData({
        kpi: { activeStudents: 0, totalMealsServed: 0, monthlyRevenue: 0, avgStudentBill: 0, todayRevenue: 0 },
        sections: ["Breakfast", "Lunch", "Snacks", "Dinner"],
        students: [],
        pagination: { currentPage: 1, pageSize: 10, totalStudents: 0, totalPages: 1 },
      });
    } finally {
      setLoading(false);
    }
  }, [organization, selectedMonth, selectedYear, searchTerm, currentPage]);

  useEffect(() => {
    fetchMonthlyLedger();
  }, [fetchMonthlyLedger]);

  /* ================= EXPORT CURRENT FILTERED DATASET ================= */
  const handleExportCSV = () => {
    const studentsList = ledgerData.students || [];
    if (studentsList.length === 0) {
      alert("No ledger data available to export for the selected filter.");
      return;
    }

    setExporting(true);

    const headers = [
      "Student ID",
      "Student Name",
      "Department",
      "Month",
      "Year",
      "Total Meals",
      "Monthly Bill (INR)",
    ];

    const rows = studentsList.map((s) => [
      `"${s.studentId}"`,
      `"${s.studentName}"`,
      `"${s.department}"`,
      `"${s.month}"`,
      `"${s.year}"`,
      s.totalMeals,
      s.monthlyBill,
    ]);

    const csvContent =
      "data:text/csv;charset=utf-8," +
      [headers.join(","), ...rows.map((e) => e.join(","))].join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute(
      "download",
      `Monthly_Billing_Register_${organization?.organizationId}_${selectedMonth}_${selectedYear}.csv`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setExporting(false);
  };

  if (!organization) return null;

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header */}
      <LedgerHeader
        orgName={organization.name}
        selectedMonth={selectedMonth}
        selectedYear={selectedYear}
        onExport={handleExportCSV}
        exporting={exporting}
      />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6 flex-1 w-full">
        {/* KPI Cards generated by Backend */}
        <LedgerStats kpi={ledgerData.kpi} />

        {/* Filter Controls */}
        <LedgerFilters
          searchTerm={searchTerm}
          onSearchChange={(val) => {
            setSearchTerm(val);
            setCurrentPage(1);
          }}
          selectedMonth={selectedMonth}
          onMonthChange={(m) => {
            setSelectedMonth(m);
            setCurrentPage(1);
          }}
          selectedYear={selectedYear}
          onYearChange={(y) => {
            setSelectedYear(y);
            setCurrentPage(1);
          }}
        />

        {/* Content Table / Loading / Empty */}
        {loading ? (
          <LedgerLoadingState />
        ) : (ledgerData.students || []).length === 0 ? (
          <LedgerEmptyState
            onResetFilters={() => {
              setSearchTerm("");
              setSelectedMonth("July");
              setSelectedYear("2026");
              setCurrentPage(1);
            }}
          />
        ) : (
          <div className="space-y-4">
            <LedgerTable
              students={ledgerData.students}
              onSelectStudent={setSelectedStudent}
            />

            <LedgerPagination
              pagination={ledgerData.pagination}
              onPageChange={setCurrentPage}
            />
          </div>
        )}
      </main>

      {/* Itemized Daily Register Drawer */}
      <LedgerDrawer
        student={selectedStudent}
        sections={ledgerData.sections}
        onClose={() => setSelectedStudent(null)}
      />
    </div>
  );
}
