import { AuthProvider } from "@/Context/AuthContext";
import "./globals.css";
import {Inter} from "next/font/google";

const inter = Inter({
  subsets : ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Food Not Waste",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
