import { AuthProvider } from "@/Context/AuthContext";
import "./globals.css";


export const metadata = {
  title: "Food Not Waste",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
